# ===== Application =====
spring.application.name=chapter6
server.port=8080

# ===== DataSource: SQL Server =====
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HSF302_CH6;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Map String sang NVARCHAR ?? h? tr? ti?ng Vi?t có d?u
spring.jpa.properties.hibernate.use_nationalized_character_data=true
# Bu?c truy c?p DB k?t thúc trong Service layer
spring.jpa.open-in-view=false

# ===== Thymeleaf & Logging =====
spring.thymeleaf.cache=false
logging.level.com.hsf302=DEBUG